CREATE DATABASE TESTEPRATICO;
GO;

USE TESTEPRATICO;
GO;

CREATE TABLE PACIENTE (
  CODPACIENTE INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
  NOME VARCHAR(50) NOT NULL UNIQUE, 
  DATNASCIMENTO DATETIME NOT NULL
);
GO;

CREATE TABLE AGENDAMENTO (
  CODAGENDAMENTO INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
  CODPACIENTE INT NOT NULL FOREIGN KEY REFERENCES PACIENTE(CODPACIENTE), 
  DATINICIOCONSULTA DATETIME NOT NULL, 
  DATFIMCONSULTA DATETIME NOT NULL, 
  OBSERVACAO VARCHAR(500)
);
GO;